const actionTypes = {
  postsActions: {
    GET_POSTS_START: "GET_POSTS_START",
    GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
    GET_POSTS_FAIL: "GET_POSTS_FAIL",
    DELETE_POSTS_START: "DELETE_POSTS_START",
    DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
    DELETE_POSTS_FAIL: "DELETE_POSTS_FAIL",
    ADD_POST: "ADD_POST",
    EDIT_POSTS: "EDIT_POSTS",
  },
};
export default actionTypes;
